---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sampleapp
  namespace: test
  labels:
    app: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: "nginx"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: test
spec:
  selector:
    app: sampleapp
  type: NodePort
  ports:
  - name: http
    targetPort: 80
    port: 80
