---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sampleapp
  namespace: default
  labels:
    app: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: "navyaa14/samplewebapp"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: default
spec:
  selector:
    app: sampleapp
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 80
